name: Deploy to EC2
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out code on Runner
              uses: action/checkout@v4

            - name: login and update the EC2 instance
              uses: appleboy/ssh-action@v1.0.3
              with:
                   host: ${{ secrets.HOST }}
                   username: ${{ secrets.USERNAME }}
                   password: ${{ secrets.PASSWORD }}
                   port: 22
                   script: |
                        hoami
                        sudo apt-get update -y







                
            #- name: Print my name
            #  run: | 
             #     echo "Kaveri"
               #   echo "GitHub"

         #   - name: Current folder
           #   run: |
              #    pwd

        
